### ISSUE TITLE
Location of oneTBB

### ISSUE THREAD

**Issue by stumarcus576** [scipopt/papilo#10]
If oneTBB is installed on Ubuntu 18.04 (or another Linux distribution) in a custom directory (e.g. in my home directory or in /tmp, as is done in the example in the link below) will PaPILO find it automatically? If not, is it possible to tell PaPILO where oneTBB is installed during the build process?

https://github.com/oneapi-src/oneTBB/blob/master/INSTALL.md

**Comment by alexhoen** [comment]
No in this case PaPILO won't find TBB. If PaPILO does not find TBB it tries to download v2021.4.0 and use this version.

If you want to use a custom directory, please set the `TBB_DIR` variable or use `cmake -DTBB_DIR=PATH_TO ..`

Hope that helps

**Comment by fschloesser** [comment]
As always, you can hint the location of your custom tbb installation at the cmake call by specifying the dir `cmake .. -DTBB_DIR=/path/to/your/custom/installation`. Sometimes you need to add `lib/cmake/` to the path.
