### ISSUE TITLE
lto1: fatal error: bytecode stream in file ‘CMakeFiles/tbbmalloc.dir/backend.cpp.o’ generated with LTO version 8.1 instead of the expected 6.2

### ISSUE THREAD

**Issue by zrjer** [scipopt/papilo#12]
Hello,
After I execute the "cmake ..." command, I was prompted that TBB was not installed and an error was reported during the installation process：
“
lto1: fatal error: bytecode stream in file ‘CMakeFiles/tbbmalloc.dir/backend.cpp.o’ generated with LTO version 8.1 instead of the expected 6.2

  compilation terminated.

  lto-wrapper: fatal error: /usr/bin/gcc returned 1 exit status

  compilation terminated.

  /usr/bin/ld: error: lto-wrapper failed

  collect2: error: ld returned 1 exit status

  make[2]: ***
  [src/tbbmalloc/CMakeFiles/tbbmalloc.dir/build.make:160：gnu_9.4_cxx11_64_relwithdebinfo/libtbbmalloc.so.2.4]
  错误 1

  make[1]: ***
  [CMakeFiles/Makefile2:205：src/tbbmalloc/CMakeFiles/tbbmalloc.dir/all]
  错误 2

  make: *** [Makefile:152：all] 错误 2
“
How can I solve this problem?

**Comment by zrjer** [comment]
But in this website https://github.com/lgottwald/PaPILO, cmake can find the installed TBB

**Comment by fschloesser** [comment]
Dear @zrjer ,
can you please provide some more information on your system and the commands that you executed? 
From what you posted it seems that you compiler and the installed tbb don't quite fit togeter. 
Best,
Franzi

**Comment by ambros-gleixner** [comment]
Please reopen if you need any further support on your build.
