### ISSUE TITLE
Default Number of Threads

### ISSUE THREAD

**Issue by stumarcus576** [scipopt/papilo#14]
What is the default number of threads used by PaPILO? Is it 1 or the number of physical cores or the number of logical cores? I don't see the number of threads used listed in the console output.

**Comment by ambros-gleixner** [comment]
The default is TBB's automatic setting, which I believe uses the number of logical cores.

**Comment by stumarcus576** [comment]
Does PaPILO's presolve and postsolve both use TBB's automatic setting?

**Comment by ambros-gleixner** [comment]
presolve yes, postsolve is sequential
