### ISSUE TITLE
Implementing .opb file parser 

### ISSUE THREAD

**Issue by freemin7** [scipopt/papilo#15]
`.opb` is a file format to specify 0-1 Integer programs. However it is already supported in the larger SCIP ecosystem. I am aware that this format also contains products of binary variables, so working with the linearization of products of binaries would be enough. I would not expect writing out `.opb`s with recovered product structures, although it would be nice.

What would be required to make papilo support reading `.opb`? 

For reference SCIP supports the following formats:
> cip, cnf, flatzinc, rlp, lp, mps, opb, pip, wbo, zimpl

I understand that supporting `flatzinc` and similar constraint based formats is really complicated and recovery of those constraint structures from a an presolved MILP quiet hard. So a full support for all filetypes SCIP can support is unrealistic given the linear framework of papilo.

**Comment by matbesancon** [comment]
As you mentioned, the number of formats supported by papilo file reading is limited because the framework considers matrix-form MILPs for now. Further combinatorial constraints (SOS{1,2} or others) will be added, quadratic constraints are thought about but not on the short-term roadmap I believe.

For MINLPs in general, one could relax the nonlinear constraints and presolve the polyhedral relaxation without dual information but this is not implemented in a systematic manner.

**Comment by ambros-gleixner** [comment]
If you would like to contribute a reader for opb, you could look at src/papilo/io/MpsParser.hpp and contribute an OpbParser.hpp. It would not be much work to integrate this. Please reopen in case you have questions or would like help how to proceed on this.

**Comment by freemin7** [comment]
When using papilo in library mode, is calling the parser a supported use case?

**Comment by freemin7** [comment]
Also what is behind that in `MpsParser.hpp`:
```
static_assert(
       num_traits<typename RealParseType<REAL>::type>::is_floating_point,
       "the parse type must be a floating point type" );
```
Is a rational parser not allowed? An integer parse would be ideal for opb but i see that accommodating that would create unnecessary complexity

**Comment by ambros-gleixner** [comment]
Yes, you can call it to create an instance of class Problem of desired arithmetic type. The MpsParser creates a Problem<REAL> and can currently only parse floating-point data, but your parser could parse integers or rationals and create from them floating-point data or rational data. PaPILO can perform exact presolving in rational arithmetic if the Problem is specified on rationals.

We have not thought about how it would work if the arithmetic type is integer only; this may not be straightforward to extend.

**Comment by freemin7** [comment]
I will go with rational then. No need to heap extra work on the presolver.
If it is fine if bother you further with questions
```
enum class RowFlag : uint8_t
{
   kLhsInf = 1 << 0,
   kRhsInf = 1 << 1,
   kEquation = 1 << 2,
   kIntegral = 1 << 3,
   kRedundant = 1 << 4,
};
```
If i have a constraint c1*x1 + c2*x3 =< b2 where x \in {0,1}^n c\in ℤ^n b \in ℤ^n what flags am i supposed to set?

**Comment by ambros-gleixner** [comment]
kLhsInf

**Comment by freemin7** [comment]
So not kIntegral?

**Comment by ambros-gleixner** [comment]
No, this flag is never used.

**Comment by freemin7** [comment]
I think i got the algorithm down and eliminated some syntax errors in the C++.

For the moment i decided to only support the linear subset of of PBO/.obp instead of "lying to the presolver" what the .obp file says. By waiting for the presolver data structures to support products of variables the existing post-solve mechanisms can be used to translate linearised solutions back to the original variables. As some solvers like Gurobi also support bilinear terms which can be used to express arbitrary products of variables, i find it better to leave the detail how products of variables are presolved to the presolver. It helps that for my usecase i do not need support for products (yet).

Can you confirm that the correct way to handle errors is to write to std out and return false from `parse( boost::iostreams::filtering_istream& file )`?

What assumptions are made about `Vec<Triplet<REAL>> entries;`  for use in `SparseStorage<REAL>`?
- Is some sorting expected?
- Are multiple entries for the same matrix element allowed or should i sum them up myself?
If a file were to contain the constraint `a1*x1 + +a3*x1 <= bi` both (index(x1), i, a1) and (index(x1), i, a3) would be added to `Vec<Triplet<REAL>> entries;`.

I am quiet unfamiliar with C++ tooling. So a pull request against my repo with how to add `PboParser.hpp` to the build process and to the code path would be welcome (or detailed instructions to the same effect) so i can actually test my implementation.

**Comment by ambros-gleixner** [comment]
For erros you should print to stderr, not stdout, see the printErrorMessage method in MpsParser.hpp.  And let parse() return false. 

Sorting is not necessary if you keep the sorted flag of the constructor false (default).

But I don't see code to deal with duplicate entries, so better add them up.

**Comment by freemin7** [comment]
Right i meant stderr not stdout. What sorting is expected with the sorted flags as true?

**Comment by ambros-gleixner** [comment]
I suppose by row index first, then column index, but i am not 100% sure.

**Comment by freemin7** [comment]
Is there some automatic formatting you use, or is formatting left up to the author?

**Comment by fschloesser** [comment]
Dear @freemin7, 
can you create a personal fork and branch off a new branch from master create with your changes?
Then the codereview can be done here in a pull request and once it's ready we will add and merge this to the internal repository. 

Formatting is described in the [online documentation](https://scipopt.org/doc/html/CODE.php).

Let me know if you need help.

Best,
Franziska

**Comment by freemin7** [comment]
Hallo @fschloesser ,

i created a personal fork [https://github.com/freemin7/papilo](https://github.com/freemin7/papilo/tree/OBP_Parser) and made a new branch called OBP_Parser. I was a bit hesitant to eagerly submit pull requests against the official repo, however i understand this is your preferred solution. Once i implemented error handling as expected by your convention and fixed the duplicate entry issue i am going to submit a pull request (unless told otherwise).

Mit freundlichen Grüßen.

**Comment by fschloesser** [comment]
If you are happier to create a pull request in your own fork, this is also fine.
The point is to have a pull request to be able to do the code review more easily.
Once the branch is ready to merge i would push it to the internal repository and merge it there. 
You can just post the link to the pull request here once you're ready for the code review.
Best,
Franzi

**Comment by fschloesser** [comment]
I had a look at your branch, can you please base your changes on the `develop`, so they go in the next major release, not in the bugfix ones?

**Comment by freemin7** [comment]
I have never rebased a git repo but now seems like a great time to learn that.

**Comment by freemin7** [comment]
Did i do the rebase mess correctly?

**Comment by fschloesser** [comment]
I will answer in the pull request
