### ISSUE TITLE
Corrected Dual Solution for Presolved Problem

### ISSUE THREAD

**Issue by stumarcus314** [scipopt/papilo#17]
Is the corrected dual solution, obtained for a presolved problem, a lower bound for the original problem? If the solution to the presolved problem is y, then let r = c-A^T*y be the reduced costs, where c and A are defined for the presolved problem. The corrected dual solution is obtained by evaluating the dual objective defined here: https://developers.google.com/optimization/lp/pdlp_math#dual

I am interested in obtaining a tight lower bound of the original problem. I do not believe PaPILO is able to save off the dual solution, so I cannot evaluate the corrected dual solution from the postsolved solution.

**Comment by ambros-gleixner** [comment]
This may depend a bit on how you integrate PaPILO in your workflow and whether the presolved problem is solved to optimality within sufficiently tight tolerances. But generally yes: PaPILO is set up to give a correct dual bound for the original problem after postsolving.

The command line interface of the postsolve command also has an option --dualsolution to save it to a file, and something similar should be available through the API.

**Comment by stumarcus576** [comment]
Does PaPILO compute and save a correct dual bound for the original problem after postsolving? Does PaPILO compute this correct dual bound by evaluating the dual objective (defined here: https://developers.google.com/optimization/lp/pdlp_math#dual) at (y,r=c-A^T*y), where c and A are defined for the original problem?

**Comment by stumarcus576** [comment]
I use PaPILO v2.1.0. I use PaPILO to presolve, PDLP (in OR-Tools v9.3) to solve the reduced problem, and PaPILO again to postsolve.  PaPILO postsolve writes neither the dual solution nor the reduced costs to files. I invoke PaPILO postsolve from the command line as shown below. 

$ papilo postsolve -v PS_fn -u rSOL_fn -l SOL_fn --dualsolution DUAL_fn --reducedcosts RC_fn

**Comment by ambros-gleixner** [comment]
Just to exclude this case: Can it be that your MPS file contains integer variables? In this case, PaPILO may apply presolving for which a dual solution cannot be recovered in postsolving (for theoretical reasons).

It may also help if you can provide a copy of your log output.

**Comment by stumarcus576** [comment]
My MPS file is a linear program (no integer variables).

**Comment by stumarcus576** [comment]
Below is the console output produced by PaPILO's presolve and postsolve.

PaPILO version 2.1.0 [mode: debug][Solvers: none][GitHash: ]
Copyright (C) 2020-2022 Zuse Institute Berlin (ZIB)

External libraries:
  Boost    1.79.0        (https://www.boost.org/)
  TBB                    Thread building block https://github.com/oneapi-src/oneTBB developed by Intel

reading took 0.785 seconds
Numerical Statistics:
 Matrix range    [1e+00,1e+00]
 Objective range [2e+01,1e+04]
 Bounds range    [1e+00,1e+00]
 RHS range       [1e+00,1e+01]
 Dynamism Variables: 1e+00
 Dynamism Rows     : 1e+00

starting presolve of problem /data/gen_MPS_files/p10_fix0_LPR.mps:
  rows:     294515
  columns:  299698
  int. columns:  0
  cont. columns:  299698
  nonzeros: 888526

round 0   ( Trivial  ):    0 del cols,    0 del rows,    0 chg bounds,    0 chg sides,    0 chg coeffs,    0 tsx applied,    0 tsx conflicts
round 1   (Exhaustive): Unchanged
activating delayed presolvers
round 2   (  Final   ): Unchanged
presolved 2 rounds:    0 del cols,    0 del rows,    0 chg bounds,    0 chg sides,    0 chg coeffs,    0 tsx applied,    0 tsx conflicts

          presolver     nb calls   success calls(%)    nb transactions     tsx applied(%)  execution time(s)
       colsingleton            2                0.0                  0                0.0              0.000
    coefftightening            0                0.0                  0                0.0              0.000
        propagation            2                0.0                  0                0.0              0.008
      simpleprobing            0                0.0                  0                0.0              0.000
       parallelrows            1                0.0                  0                0.0              0.020
       parallelcols            1                0.0                  0                0.0              0.029
           stuffing            1                0.0                  0                0.0              0.001
            dualfix            1                0.0                  0                0.0              0.007
      fixcontinuous            1                0.0                  0                0.0              0.001
       simplifyineq            0                0.0                  0                0.0              0.000
        doubletoneq            1                0.0                  0                0.0              0.003
            implint            0                0.0                  0                0.0              0.000
             domcol            1                0.0                  0                0.0              0.017
          dualinfer            1                0.0                  0                0.0              0.094
            probing            0                0.0                  0                0.0              0.000
       substitution            1                0.0                  0                0.0              0.048
           sparsify            1                0.0                  0                0.0              0.003

found 101 equations, checking for linear dependency
preprocessed LU factor has 299799 nonzeros, preprocessing removed 0 rows/cols
calling LUSOL on remaining factor
0 equations are redundant, factorization took 0.025485106 seconds
reduced problem:
  reduced rows:     294515
  reduced columns:  299698
  reduced int. columns:  0
  reduced cont. columns:  299698
  reduced nonzeros: 888526

presolving finished after 0.307 seconds

reduced problem written to /data/PaPILO_files/p10_fix0_red.mps in 0.469 seconds

postsolve archive written to /data/PaPILO_files/p10_fix0_red.postsolve in 0.104 seconds

File        : '/data/PaPILO_files/p10_fix0_red.mps'
Solver      : PDLP_LINEAR_PROGRAMMING
Dimension   : 294515 x 299698
Status      : MPSOLVER_OPTIMAL
Objective   : 1.801141147736736e+05
BestBound   :             inf
Iterations  : 4992
Time        : 82.72
PDLP time: 84.245723244 [s].
PaPILO version 2.1.0 [mode: debug][Solvers: none][GitHash: ]
Copyright (C) 2020-2022 Zuse Institute Berlin (ZIB)

External libraries:
  Boost    1.79.0        (https://www.boost.org/)
  TBB                    Thread building block https://github.com/oneapi-src/oneTBB developed by Intel

file /data/PaPILO_files/p10_fix0_reducedcosts.sol is not valid

**Comment by ambros-gleixner** [comment]
Okay, from what I see, the command line interface does not yet offer the possibility to read dual multipliers and reduced cost values. The --dualsolution and --reducedcosts option are placeholders for output. This is confusing, apologees!

So the feature to read and postsolve dual solutions for LPs is only available through the C++ API.

The main developer for this is on leave until the end of the year, but then we can add this. We should integrate dual multipliers for rows simply in the file passed by the -l option, I suppose. If you need it quickly and want to contribute yourself: the SolParser::read() method would need to be extended by the origrow_mapping of the PostsolveStorage. But it is a bit tricky, because subsequently the reduced costs would need to be computed and I am not fully sure where this should best happen.

**Comment by stumarcus576** [comment]
What rules does PaPILO use to translate from the presolved space to the original space? This would be useful to translate the corrected dual objective value from the presolved space to the original space.

**Comment by ambros-gleixner** [comment]
It runs through the postsolve stack in reverse order and applies appropriate modifications to the primal and dual solution in order to maintain the KKT conditions. Which transformations these are depends on the presolving steps, of which there are many. Especially for the dual solution, this is too technical and there are too many cases to explain here.

However, if you are only interested in the dual objective value, I am wondering whether it may be sufficient to just subtract the objective offset that comes from fixing, aggregating, etc. variables. You should get this as `Problem::getObjective().offset`.

**Comment by stumarcus576** [comment]
Is the transformation (of the corrected dual objective value) from the presolved space to the original space affected if we only solve the LP relaxation of the presolved MILP instead of the presolved MILP?

**Comment by ambros-gleixner** [comment]
Probably not, I think it should work, too. But please let us know your observations.

**Comment by alexhoen** [comment]
hi @stumarcus314,

first of all, PDLP is integrated into PaPILO and it may be more convenient to build PaPILO with PDLP and use it via cl.

To calculate the dual solution for the original solution the solver must provide a dual solution for the reduced problem. Then PaPILO is able to reconstruct the primal and the dual solution for the variables deleted in the presolving step. PDLP obviously does not provide such information and unfortunately PaPILO is not able to perform magic in this case. Therefore saving the non exisiting reduced costs is ignored. I guess a hint in this case that it is skipped may be definitely useful.

Using a simplex solver which provides such information the reduced costs are saved:

`/home/alexander/git_repositories/papilo/cmake-build-debug/bin/papilo solve -f /home/alexander/git_repositories/soplex/check/instances/adlittle.mps -c re.sol -p /home/alexander/git_repositories/papilo/settings/lp_presolvers_with_basis.set -l test.sol
PaPILO version 2.1.0 [mode: optimized][Solvers: SoPlex][GitHash: 22170fdb]
Copyright (C) 2020-2022 Zuse Institute Berlin (ZIB)

External libraries: 
  Boost    1.78.0 	 (https://www.boost.org/)
  TBB            	 Thread building block https://github.com/oneapi-src/oneTBB developed by Intel
  GMP      6.2.0  	 GNU Multiple Precision Arithmetic Library developed by T. Granlund (gmplib.org)
  SoPlex   6.0.1 	 Linear Programming Solver developed at Zuse Institute Berlin (soplex.zib.de) [GitHash: 687944bf]

reading took 0.00584 seconds
Numerical Statistics:
 Matrix range    [1e-02,6e+01]
 Objective range [2e+00,3e+03]
 Bounds range    [0e+00,0e+00]
 RHS range       [2e+00,2e+03]
 Dynamism Variables: 2e+03
 Dynamism Rows     : 8e+02
set presolve.componentsmaxint = -1
set presolve.detectlindep = 0
set doubletoneq.enabled = 0
set dualinfer.enabled = 0
set substitution.enabled = 0
set sparsify.enabled = 0

starting presolve of problem /home/alexander/git_repositories/soplex/check/instances/adlittle.mps:
  rows:     56
  columns:  97
  int. columns:  0
  cont. columns:  97
  nonzeros: 383

round 0   ( Trivial  ):    2 del cols,    3 del rows,    4 chg bounds,    0 chg sides,    0 chg coeffs,    0 tsx applied,    0 tsx conflicts
round 1   (   Fast   ):    3 del cols,    3 del rows,   90 chg bounds,    1 chg sides,    1 chg coeffs,  195 tsx applied,    0 tsx conflicts
round 2   (   Fast   ):    3 del cols,    3 del rows,  105 chg bounds,    1 chg sides,    1 chg coeffs,  231 tsx applied,    0 tsx conflicts
round 3   (Exhaustive):    3 del cols,    3 del rows,  109 chg bounds,    1 chg sides,    1 chg coeffs,  240 tsx applied,    0 tsx conflicts
round 4   (  Final   ): Unchanged
presolved 4 rounds:    3 del cols,    3 del rows,  109 chg bounds,    1 chg sides,    1 chg coeffs,  240 tsx applied,    0 tsx conflicts

          presolver     nb calls   success calls(%)    nb transactions     tsx applied(%)  execution time(s) 
       colsingleton            4               25.0                  1              100.0              0.000
    coefftightening            0                0.0                  0                0.0              0.000
        propagation            4               75.0                238              100.0              0.000
      simpleprobing            0                0.0                  0                0.0              0.000
       parallelrows            1                0.0                  0                0.0              0.000
       parallelcols            1                0.0                  0                0.0              0.000
           stuffing            1                0.0                  0                0.0              0.000
            dualfix            2               50.0                  1              100.0              0.000
      fixcontinuous            1                0.0                  0                0.0              0.000
       simplifyineq            0                0.0                  0                0.0              0.000
        doubletoneq            0                0.0                  0                0.0              0.000
            implint            0                0.0                  0                0.0              0.000
             domcol            1                0.0                  0                0.0              0.000
          dualinfer            0                0.0                  0                0.0              0.000
            probing            0                0.0                  0                0.0              0.000
       substitution            0                0.0                  0                0.0              0.000
           sparsify            0                0.0                  0                0.0              0.000

reduced problem:
  reduced rows:     53
  reduced columns:  94
  reduced int. columns:  0
  reduced cont. columns:  94
  reduced nonzeros: 372

presolving finished after 0.022 seconds

Equilibrium scaling LP (persistent)
Simplifier removed 0 rows, 0 columns, 0 nonzeros, 0 col bounds, 0 row bounds
Reduced LP has 53 rows 94 columns 372 nonzeros
Equilibrium scaling LP
type |   time |   iters | facts |    shift | viol sum | viol num | obj value 
  L  |    0.0 |       0 |     3 | 0.00e+00 | 1.35e+03 |       26 | -5.17875028e+05
  L  |    0.0 |     121 |     5 | 0.00e+00 | 0.00e+00 |        0 | 2.25494963e+05
 --- unscaling internal solution
 --- unsimplifying solution and basis
 --- unscaling external solution
 --- verifying computed solution
  L  |    0.0 |       0 |     1 | 0.00e+00 | 0.00e+00 |        0 | 2.25494963e+05
  L  |    0.0 |       0 |     1 | 0.00e+00 | 0.00e+00 |        0 | 2.25494963e+05
 --- unscaling external solution
 --- verifying computed solution

SoPlex status       : problem is solved [optimal]
Solving time (sec)  : 0.06
Iterations          : 121
Objective value     : 2.25494963e+05

Solution passed validation

postsolve finished after 0.001 seconds
feasible: true
objective value: 225494.963162380

violations:
  bounds:      0.00000000000000
  constraints: 0.00000000000000
  integrality: 0.00000000000000

solution written to file test.sol in 0.000618 seconds
reduced solution written to file re.sol in 0.000451 seconds

solving finished after 0.022 seconds

Process finished with exit code 0`

**Comment by alexhoen** [comment]
I just wanted to point out, that if the reduced problem provides a dual solution (including reduced costs and optional basis information) then PaPILO is able to process this information. In the example above the dual solution is calculated but not saved since there was no such call in the command line. To answer your question:

> Is the dual solution also saved? Does the --dualsolution argument work in PaPILO?

Not per default only when the user provides a file per  --dualsolution. (Then it works as designed)

For example, extending the call above :
`/home/alexander/git_repositories/papilo/cmake-build-debug/bin/papilo solve -f /home/alexander/git_repositories/soplex/check/instances/adlittle.mps -c re.sol -p /home/alexander/git_repositories/papilo/settings/lp_presolvers_with_basis.set -l test.sol --dualsolution dual.sol -w basis.sol`

results in:

`solution written to file test.sol in 0.000428 seconds
dual solution written to file dual.sol in 0.000327 seconds
reduced solution written to file re.sol in 0.000391 seconds
basis written to file basis.sol in 0.000182 seconds`

**Comment by mlubin** [comment]
> PDLP obviously does not provide such information and unfortunately PaPILO is not able to perform magic in this case.

Just to clarify, PDLP does return duals and reduced costs, as one might expect of an LP solver. The [`SolverResult`](https://github.com/google/or-tools/blob/stable/ortools/pdlp/primal_dual_hybrid_gradient.h#L61) struct contains fields for `dual_solution` and `reduced_costs`. `SolverResult` is returned by `PrimalDualHybridGradient`, example [here](https://github.com/google/or-tools/blob/stable/examples/cpp/pdlp_solve.cc#L93).

**Comment by alexhoen** [comment]
Thanks for the clarification :+1: . PaPILO parses now the dual solution and the reduced costs from or-tools.

**Comment by alexhoen** [comment]
@stumarcus314 
we extended the `postsolve` call to be able to pass also the dual solution via cml, the reduced costs and the basis information (optional). Then PaPILO can also recalculate the (basis) solution if necessary. The call would look like the following:

`build/bin/papilo postsolve -v kb2.postsolve -u kb2_primal.solution --dual-reduced-solution kb2_dual.solution --costs-reduced-solution kb2_reduced.solution --dualsolution orig_dual.solution --basis-reduced-solution kb2.bas`

It will be only tomorrow on the `develop`branch

**Comment by stumarcus314** [comment]
@alexhoen @mlubin 
Is it possible for PaPILO to compute and report the corrected dual objective during postsolve in order to provide a lower bound for the original problem? The corrected dual objective is computed by evaluating the dual objective (defined here: https://developers.google.com/optimization/lp/pdlp_math#dual) at (y , r=c-A^T * y), where y is the postsolved dual solution (i.e., the dual solution for the orignal problem), r = c-A^T * y are the postsolved reduced costs (i.e., the reduced costs for the orignal problem), and c and A are defined for the original problem.

**Comment by mlubin** [comment]
I'm not familiar with how PDLP is connected to PaPILO via the API. For the command line, the starting point would be [here](https://github.com/google/or-tools/blob/stable/examples/cpp/pdlp_solve.cc) where you could modify the code to write the dual solution and reduced costs, then follow @alexhoen's `postsolve` example above.
Depending on how paranoid you are, you could recompute r = c - A^Ty, where y is the postsolved dual solution (returned by PaPILO), and then compute the objective value to ensure it's mathematically correct (i.e., corresponding to a feasible dual solution).

**Comment by alexhoen** [comment]
> Is it possible for PaPILO to compute and report the corrected dual objective during postsolve in order to provide a lower bound for the original problem?

Unfortunately not. But I see no problem computing the dual objective if you have r and y. See Miles's comment on how to obtain them.

**Comment by stumarcus314** [comment]
If one only wants to compute and save the postsolved dual solution during postsolve, does PaPILO only require the presolved dual solution (or does PaPILO also require the presolved primal solution)?

**Comment by alexhoen** [comment]
PaPILO needs the primal, dual and the reduced costs.
But if you build PaPILO with ortools (cmake -DGLOP=yourpathtoortools ..) then PaPILO accesses the solutions from Ortools automatically. In this case you just can need to modify the preserve command slightly by replacing the presolve with solve and add the file to store the dual solution.
You can see the example in the Readme for SCIP.

**Comment by stumarcus314** [comment]
Will the solve command approach, where PaPILO is built with OR-Tools, only work on the develop branch?
Did you mean to write "modify the presolve command" instead of "modify the preserve command"?

**Comment by alexhoen** [comment]
> Will the solve command approach, where PaPILO is built with OR-Tools, only work on the develop branch?

Yes. But there should be no drawback in using the develop branch 


> Did you mean to write "modify the presolve command" instead of "modify the preserve command"?

Yes sorry missed to check auto correction.
