### ISSUE TITLE
Chicken-and-egg problem: papilo links to SCIP, and SCIP links to papilo

### ISSUE THREAD

**Issue by yurivict** [scipopt/papilo#2]
Both projects have options to link with each other.

**Comment by 1hoen** [comment]
You can use PaPILO in 3 different ways:
1. as standalone presolving library
2. as a frontend for solvers. In this case, PaPILO presolves the problem and passes the presolved problem to a solver via MIP
3. integrated into a solver. In this case, PaPILO would be part of the presolving routine. In this case PaPILO would never call an integrated solver - even if it is built with that.
