### ISSUE TITLE
Presolve killed

### ISSUE THREAD

**Issue by stumarcus314** [scipopt/papilo#26]
PaPILO is killed while trying to presolve a MILP model stored in a 9.6 GB MPS file. The computer has a AMD Ryzen Threadripper 3960X 24-Core Processor, which has 48 logical cores due to hyper-threading, has 128 GB RAM, and runs Ubuntu 20.04.5 LTS. Is PaPILO running out of memory? 

$ /home/muck/papilo-2.1.0/build/bin/papilo presolve -f /data/muck/gen_MPS_files/p10_fix0_MILP_binary_x.mps -r /data/muck/PaPILO_files_MILP_binary_x/p10_fix0_red.mps -v /data/muck/PaPILO_files_MILP_binary_x/p10_fix0_red.postsolve
PaPILO version 2.1.0 [mode: debug][Solvers: none][GitHash: ]
Copyright (C) 2020-2022 Zuse Institute Berlin (ZIB)

External libraries:
  Boost    1.79.0        (https://www.boost.org/)
  TBB                    Thread building block https://github.com/oneapi-src/oneTBB developed by Intel

reading took 188.0 seconds
Numerical Statistics:
 Matrix range    [1e+00,1e+00]
 Objective range [2e+01,1e+04]
 Bounds range    [1e+00,1e+00]
 RHS range       [1e+00,1e+01]
 Dynamism Variables: 1e+00
 Dynamism Rows     : 1e+00

starting presolve of problem /data/muck/gen_MPS_files/p10_fix0_MILP_binary_x.mps:
  rows:     47261300
  columns:  47251695
  int. columns:  47251695
  cont. columns:  0
  nonzeros: 141744517

round 0   ( Trivial  ):    2 del cols, 14889 del rows,    2 chg bounds,    0 chg sides,    0 chg coeffs,    0 tsx applied,    0 tsx conflicts
Killed

**Comment by alexhoen** [comment]
we are also struggling with presolving instances of this size, for example, https://miplib.zib.de/instance_details_hawaiiv10-130.html.

I would guess from the log that the process was killed because it allocated too much memory: https://stackoverflow.com/questions/726690/what-killed-my-process-and-why

But, PaPILO is able to at least load the problem and execute a first presolve round, so maybe there is a way to solve this problem:

1. `presolve.compressfac = 1` I would increase the compress factor to 1 so that all deleted rows (and columns) are removed and their storage is freed. I don't think that 15k deleted rows will free up that much memory but it is at least something. 
2. All presolvers run in parallel and each will need some memory to execute their method. For example, Parallel Row and Column will compute a hash value for each row respectively, column. So to ensure that only one presolver at a time reserves memory it maybe worth a try to run PaPILO in sequential mode and apply the results immediately after the presolver finished. _(this would not make use of the feature of PaPILO but ...)_ See also section 3.3 for more information https://arxiv.org/abs/2206.10709
```
# maximal number of threads to use (0: automatic)  [Integer: [0,2147483647]]
presolve.threads = 1

# if only one thread (presolve.threads = 1) is used, apply the reductions immediately afterwards
presolve.apply_results_immediately_if_run_sequentially = 1
```

Please let me know if this helps

**Comment by stumarcus314** [comment]
Where do I set those option parameters?

**Comment by stumarcus314** [comment]
Your second suggestion resolved the problem.

$ /home/muck/papilo-2.1.0/build/bin/papilo presolve -f /data/muck/gen_MPS_files/p10_fix0_MILP_binary_x.mps -r /data/muck/PaPILO_files_MILP_binary_x/p10_fix0_red.mps -v /data/muck/PaPILO_files_MILP_binary_x/p10_fix0_red.postsolve --presolve.threads=1 --presolve.apply_results_immediately_if_run_sequentially=1
PaPILO version 2.1.0 [mode: debug][Solvers: none][GitHash: ]
Copyright (C) 2020-2022 Zuse Institute Berlin (ZIB)

External libraries:
  Boost    1.79.0        (https://www.boost.org/)
  TBB                    Thread building block https://github.com/oneapi-src/oneTBB developed by Intel

reading took 188.0 seconds
Numerical Statistics:
 Matrix range    [1e+00,1e+00]
 Objective range [2e+01,1e+04]
 Bounds range    [1e+00,1e+00]
 RHS range       [1e+00,1e+01]
 Dynamism Variables: 1e+00
 Dynamism Rows     : 1e+00
set presolve.threads = 1
set presolve.apply_results_immediately_if_run_sequentially = 1

starting presolve of problem /data/muck/gen_MPS_files/p10_fix0_MILP_binary_x.mps:
  rows:     47261300
  columns:  47251695
  int. columns:  47251695
  cont. columns:  0
  nonzeros: 141744517

round 0   ( Trivial  ):    2 del cols, 14889 del rows,    2 chg bounds,    0 chg sides,    0 chg coeffs,    0 tsx applied,    0 tsx conflicts
round 1   (Exhaustive): 14889 del cols, 14891 del rows,    2 chg bounds, 14885 chg sides, 14885 chg coeffs, 14887 tsx applied,    0 tsx conflicts
activating delayed presolvers
round 2   (  Final   ): Unchanged
presolved 2 rounds: 14889 del cols, 14891 del rows,    2 chg bounds, 14885 chg sides, 14885 chg coeffs, 14887 tsx applied,    0 tsx conflicts

          presolver     nb calls   success calls(%)    nb transactions     tsx applied(%)  execution time(s)
       colsingleton            2               50.0              14887              100.0              0.142
    coefftightening            2                0.0                  0                0.0              1.221
        propagation            2                0.0                  0                0.0              1.269
      simpleprobing            1                0.0                  0                0.0              0.149
       parallelrows            1                0.0                  0                0.0             10.312
       parallelcols            1                0.0                  0                0.0             10.975
           stuffing            1                0.0                  0                0.0              0.010
            dualfix            1                0.0                  0                0.0              0.969
      fixcontinuous            0                0.0                  0                0.0              0.000
       simplifyineq            1                0.0                  0                0.0              1.788
        doubletoneq            1                0.0                  0                0.0              1.778
            implint            0                0.0                  0                0.0              0.000
             domcol            1                0.0                  0                0.0              2.308
          dualinfer            0                0.0                  0                0.0              0.000
            probing            1                0.0                  0                0.0             75.544
       substitution            1                0.0                  0                0.0              0.561
           sparsify            1                0.0                  0                0.0              0.209

reduced problem:
  reduced rows:     47246409
  reduced columns:  47236806
  reduced int. columns:  47236806
  reduced cont. columns:  0
  reduced nonzeros: 141699850

presolving finished after 159.299 seconds

reduced problem written to /data/muck/PaPILO_files_MILP_binary_x/p10_fix0_red.mps in 74.981 seconds

postsolve archive written to /data/muck/PaPILO_files_MILP_binary_x/p10_fix0_red.postsolve in 15.698 seconds

**Comment by alexhoen** [comment]
ok that's nice though the presolvers weren't that effective.
You can find the parameters in this file https://github.com/scipopt/papilo/blob/master/parameters.txt in the repository with a brief and hopefully understandable explanation.

I am curious: for what are you using PaPILO? You can write me an email hoen@zib.de if you like.

**Comment by stumarcus314** [comment]
The original MPS file is 9.6 GB, while the presolved MPS file is 12 GB! Why is the presolved model larger?
