### ISSUE TITLE
The permutation of constraints and variables can cause infeasible.

### ISSUE THREAD

**Issue by liangbug** [scipopt/papilo#29]
I am dealing with a problem on SCIP 8.0.3, but it can't get the optimal value, which turns out infeasible. I permutate constraints and variables, then get the optimal value.
What may cause it to happen? Are there any suggestions to prevent this error?

**Comment by liangbug** [comment]
I have verified that SCIP 8.0.3 with newest master version of PaPILO returns the correct solution. 

https://github.com/scipopt/scip/blob/5ecb558e560388c9786affaf5c9ca662c36cfd02/src/scip/presol_milp.cpp#L367   https://github.com/scipopt/scip/blob/5ecb558e560388c9786affaf5c9ca662c36cfd02/src/scip/presol_milp.cpp#L375

**Comment by alexhoen** [comment]
Perfect!! The bugfix will go live with the next bugfix release. 

SCIP loads the presolving techniques and defines its own order (see https://www.scipopt.org/doc/html/presol__milp_8cpp_source.php line 346ff). Therefore, the order should stay and obviously stay the same. This was "only" the check if the presolving techniques simple-probing generates valid reductions. Regardless of the order of presolvers, this should be the case for all presolvers. We will change the order in SCIP probably with the next bugfix release

I will close this ticket now. If you have questions feel free to contact us!

Many thanks you too.
