### ISSUE TITLE
Building with OR-Tools

### ISSUE THREAD

**Issue by stumarcus314** [scipopt/papilo#33]
What is the cmake flag ("-DORTOOLS_DIR=" ?) to specify the location of OR-Tools when trying to build PaPILO with OR-Tools in order to use GLOP and PDLP? Will CP-SAT also be added as a possible OR-Tools solver integrated with PaPILO? CP-SAT can solve pure integer linear programs.

mkdir build
cd build
cmake -DORTOOLS_DIR=PATH_TO_ORTOOLS_BUILD_DIR ..
make

**Comment by alexhoen** [comment]
If you have it installed globally the -DGLOP=on is sufficient otherwise yoh can customize the directory by GLOP_DIR.
 Currently glop and pdlp are supported which can be selected via parameter ortools.solverid .

**Comment by stumarcus314** [comment]
If OR-Tools is updated, rebuilt, and re-installed but the installation directory does not change, must PaPILO also be rebuilt?

**Comment by alexhoen** [comment]
Yes
