### ISSUE TITLE
vector out of bounds access at Presolve.hpp line 1152

### ISSUE THREAD

**Issue by tobiass-sdl** [scipopt/papilo#34]
https://github.com/scipopt/papilo/blob/2836a3d8f4bc9fa24ff5467939c9952ba3ae3dbe/src/papilo/core/Presolve.hpp#L1152
```
   for( ; k != static_cast<int>( reds.size() ); ++k )
   {
      result = probUpdate.applyTransaction( &reds[k], &reds.data()[k + 1] );
```
reds.data()[k+1] is clearly out of bounds in the last iteration of this loop. If compiled with Visual C++ in debug mode, an assert will be triggered within th VC++ implementation of std::vector.

**Comment by alexhoen** [comment]
yes `reds.data()[k+1] ` is out of bounds. If you take a look at the implementation of `applyTransactions` , then you will see that it loops over the elements from `&reds[k]` to (but not including) `&red.data()[k+1]`.

Nevertheless, besides displayed warning the code should compile and run with without further complaints. From your message it seems that is not the case. Could you please describe the failing assert more detailed?

**Comment by tobiass-sdl** [comment]
actually I'm working with papilo 2.1.2, where it is not reds.data()[k+1] but reds[k+1].
As mentioned, there is 
https://github.com/microsoft/STL/blob/15aea9852b557f70821651600e51d9a2b3b1a95e/stl/inc/vector#L3197
inside Microsoft's STL - _CONTAINER_DEBUG_LEVEL is turned on by visual c++ for debug builds. Therefore debug builds of papilo 2.1.2 will always terminate the process at this line.

I guess I have to switch to master, the trick with .data() should work around that assert.

**Comment by alexhoen** [comment]
ah did not see that you were not on the newest branch. 

Guess that is going to fix is. please report if not.

**Comment by tobiass-sdl** [comment]
yes, with master debug builds work.
