### ISSUE TITLE
PaPILO Presolve: Objective Function Value

### ISSUE THREAD

**Issue by stumarcus314** [scipopt/papilo#35]
Does PaPILO presolve change the objective function value between the original and presolved space? That is, if the PaPILO presolved model is solved to optimality, is the optimal objective value in the presolved space the same as that in the original space? If not, is there a simple way to transform the objective value in the presolved space to the objective value in the original space?

**Comment by alexhoen** [comment]
> Does PaPILO presolve change the objective function value between the original and presolved space? 

yes 

> That is, if the PaPILO presolved model is solved to optimality, is the optimal objective value in the presolved space the same as that in the original space? 

I am not sure what you mean by space. Both are obvious real numbers and hence in R. The reduced problem and the original problem have the same objective value if you consider the offset of the fixed variables - which some solvers might not be able to process.

Does that answer your question?

**Comment by stumarcus314** [comment]
If all the fixed variables appearing in the objective are fixed to 0 by PaPILO, then will the objective values be the same between the reduced and original problems?

**Comment by alexhoen** [comment]
The values of the variables are stored in the objective offset. Hence yes

**Comment by stumarcus314** [comment]
Is there an easy way to access the objective offset, so that one could apply this (add or substract) to the objective value found by the solution to the reduced problem to get the corresponding objective value in the original space?

**Comment by alexhoen** [comment]
You maybe should Tell me how you  use Papilo. In case you are writing the reduced problem to a mps file the objective offset is present in the objective as you can see in the file

**Comment by stumarcus314** [comment]
Where in the reduced MPS file is the offset between the original and reduced problems? How does one find how a variable in the original problem (e.g., y[3447]) is mapped into a variable in the reduced problem?

$ head -100 p12_fix0_MILP_binary_x_red.mps
*ROWS:         9852560
*COLUMNS:      9850704
*INTEGER:      9850704
*NONZERO:      29526114
*
*
NAME          /data/p12_fix0_MILP_binary_x.mps
ROWS
 N  OBJ
 L  off_x[1,10]
 L  off_x[1,18]
 L  off_x[1,38]
 L  off_x[1,40]
 L  off_x[1,46]
 L  off_x[1,51]
 L  off_x[1,52]
 L  off_x[1,59]
 L  off_x[1,61]
 L  off_x[1,65]
 L  off_x[1,70]
 L  off_x[1,77]
 L  off_x[1,79]
 L  off_x[1,80]
 L  off_x[1,90]
 L  off_x[1,92]
 L  off_x[1,93]
 L  off_x[1,103]
 L  off_x[1,116]
 L  off_x[1,118]
 L  off_x[1,143]
 L  off_x[1,145]
 L  off_x[1,149]
 L  off_x[1,152]
 L  off_x[1,154]
 L  off_x[1,162]
 L  off_x[1,172]
 L  off_x[1,177]
 L  off_x[1,179]
 L  off_x[1,183]
 L  off_x[1,185]
 L  off_x[1,198]
 L  off_x[1,206]
 L  off_x[1,211]
 L  off_x[1,212]
 L  off_x[1,217]
 L  off_x[1,224]
 L  off_x[1,241]
 L  off_x[1,242]
 L  off_x[1,250]
 L  off_x[1,261]
 L  off_x[1,263]
 L  off_x[1,284]
 L  off_x[1,298]
 L  off_x[1,304]
 L  off_x[1,316]
 L  off_x[1,319]
 L  off_x[1,325]
 L  off_x[1,326]
 L  off_x[1,329]
 L  off_x[1,330]
 L  off_x[1,331]
 L  off_x[1,340]
 L  off_x[1,342]
 L  off_x[1,349]
 L  off_x[1,350]
 L  off_x[1,356]
 L  off_x[1,358]
 L  off_x[1,365]
 L  off_x[1,366]
 L  off_x[1,367]
 L  off_x[1,368]
 L  off_x[1,369]
 L  off_x[1,414]
 L  off_x[1,419]
 L  off_x[1,420]
 L  off_x[1,436]
 L  off_x[1,438]
 L  off_x[1,444]
 L  off_x[1,448]
 L  off_x[1,454]
 L  off_x[1,457]
 L  off_x[1,459]
 L  off_x[1,460]
 L  off_x[1,466]
 L  off_x[1,474]
 L  off_x[1,485]
 L  off_x[1,487]
 L  off_x[1,490]
 L  off_x[1,494]
 L  off_x[1,502]
 L  off_x[1,508]
 L  off_x[1,514]
 L  off_x[1,515]
 L  off_x[1,523]
 L  off_x[1,525]
 L  off_x[1,526]
 L  off_x[1,528]
 L  off_x[1,533]
 L  off_x[1,534]
 L  off_x[1,535]

**Comment by alexhoen** [comment]
all reduced variable have the same name as in the original file. If they were removed they are not present anymore.

Search for the term "OBJ" in the file like described by cplex: https://perso.ensta-paris.fr/~diam/ro/online/cplex/cplex1271/CPLEX/FileFormats/topics/MPS_ext_objsen.html

**Comment by stumarcus314** [comment]
Thanks. I found the objective offset in the reduced MPS file.

RHS
    B         OBJ       -62917465.0000000
