### ISSUE TITLE
Tagged release for v2.1.3

### ISSUE THREAD

**Issue by stumarcus314** [scipopt/papilo#37]
Are you planning to make a release for PaPILO v2.1.3, which is provided with SCIP v8.0.4? https://scipopt.org/

**Comment by alexhoen** [comment]
Yes. Only the tag is missing. Unfortunately, the tags do not get mirrored and needs to be manually.

**Comment by ju-manns** [comment]
I just pushed the tag. Thank you for raising this with us!
