### ISSUE TITLE
Integration with COPT

### ISSUE THREAD

**Issue by stumarcus314** [scipopt/papilo#38]
Have you considered integrating PaPILO with COPT? COPT is competitive with Gurobi according to the benchmarks linked below. At least for now, COPT has a generous license.
Benchmarks: https://plato.asu.edu/bench.html
COPT software: https://github.com/COPT-Public/COPT-Release
COPT license: https://www.shanshu.ai/copt/
COPT user guide: https://guide.coap.online/copt/en-doc/index.html

**Comment by alexhoen** [comment]
Currently, we are have no plans in that regard. But, PaPILO is a free project and any contribution would be welcomed 😊
