### ISSUE TITLE
CMake config fails with Boost IOStreams

### ISSUE THREAD

**Issue by glebbelov** [scipopt/papilo#4]
Ubuntu 20.10. Running `cmake ..` all fine but I noticed boost/iostreams,serialization,program_options were not found. I installed them, reran cmake. Then ran it with `-DCMAKE_BUILD_TYPE=Release`. Still successful. Then ran `cmake.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=on` and got the below error.

Strangely, wiping out the build directory, and even re-cloning papilo and deinstalling the optional boost components did not help.

...
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: iostreams serialization program_options 
-- Performing Test PAPILO_USE_BOOST_IOSTREAMS_WITH_ZLIB
-- Performing Test PAPILO_USE_BOOST_IOSTREAMS_WITH_ZLIB - Success
-- Performing Test PAPILO_USE_BOOST_IOSTREAMS_WITH_BZIP2
-- Performing Test PAPILO_USE_BOOST_IOSTREAMS_WITH_BZIP2 - Success
-- Linking solvers: SCIP
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: serialization program_options iostreams 
-- Configuring done
CMake Error at binaries/CMakeLists.txt:53 (add_executable):
  Target "papilo-executable" links to target "ZLIB::ZLIB" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

**Comment by fschloesser** [comment]
Here a list of all packages that we install on our build environment on ubuntu20, i think you need `zlib1g-dev`:
wget cmake g++ m4 xz-utils libgmp-dev unzip zlib1g-dev libtbb-dev libreadline-dev pkg-config git liblapack-dev libgsl-dev flex bison libcliquer-dev gfortran file dpkg-dev libopenblas-dev rpm

**Comment by fschloesser** [comment]
@glebbelov do you have an update?

**Comment by glebbelov** [comment]
Hi Franziska,

this time, in a new Ubuntu 20.10, I compiled without libboost-dev-all at
first, all worked. Then I installed -dev-all, reran cmake, again all fine.

However then I noticed that papilo is now part of scipoptsuite. I'll try to
follow that path.

What IDEs do you use? I noticed MSVC and VS Code go hard with templates.

Best regards,
Gleb

**Comment by fschloesser** [comment]
On windows we compile papilo with cmake option `-G"Visual Studio 15 2017 Win64"` on a batch commandline after setting `cmake -E env CXXFLAGS="/w /Zc:__cplusplus" CFLAGS="/w"`. 
On ubuntu we test with gcc and clang and haven't had problems with templates. As to an IDE @1hoen will have to give you a hint.

**Comment by 1hoen** [comment]
I am currently using CLION and am not facing any problems there.
