### ISSUE TITLE
PDLP GPU

### ISSUE THREAD

**Issue by stumarcus314** [scipopt/papilo#41]
There is a C implementation of the LP method PDLP that runs on an Nvidia GPU. Are there plans to integrate/link this GPU LP solver into PaPILO?
https://arxiv.org/abs/2311.12180
https://github.com/jinwen-yang/cuPDLP.jl
https://github.com/COPT-Public/cuPDLP-C

**Comment by alexhoen** [comment]
No, currently we have no such plans...
