### ISSUE TITLE
PaPILO with GLOP or PDLP

### ISSUE THREAD

**Issue by stumarcus314** [scipopt/papilo#43]
If PaPILO is built with OR-Tools and the solve command is used to solve an LP (papilo solve -f problem.mps -l problem.sol), does PaPILO write the presolved problem to an MPS file and then call GLOP or PDLP on the presolved MPS file? From the command line, how does one select whether solve uses GLOP vs PDLP?

**Comment by alexhoen** [comment]
In this case the presolved problem is not stored. It just passes the problem through the API of the solver. 

To switch between the solvers one can use the parameter `ortools.solver_id = GLOP` . PDLP should be the default.

**Comment by stumarcus314** [comment]
Is ortools.solver_id = GLOP a PaPILO command line argument?

**Comment by alexhoen** [comment]
No, part of the parameter.txt file

papilo solve -f problem.mps -l problem.sol -p parameter.txt
