### ISSUE TITLE
Boost libraries are required even if Papilo is used as header-only library (at least on windows)

### ISSUE THREAD

**Issue by tobiass-sdl** [scipopt/papilo#46]
This is due to boost auto linking:

* Postsolve.hpp, PostsolveStorage.hpp, Presolve.hpp and MultiPrecision.hpp include stuff from boost serialization
* Those include transitively boost/config/auto_link.hpp which has pragmas to tell the compiler/linker to link against boost libraries. This completely bypases cmake or whatever other build system you use.
* as a consequence the build fails with a linker error if those boost libraries are not available.

Not sure which compilers are affected. I'm using MSVC and Papilo 2.2.0.

Workaround:
 removing those includes in the for files mentioned above worked for me. Not sure whether there are cases they are needed.

**Comment by alexhoen** [comment]
hi,
Serialization in PaPILO is necessary to store the postsolve operation in the postsolve file.
Can you post the entire error and the boost version you are using here? 
Also it would be great if you could share the changes you performed. 
BG

**Comment by tobiass-sdl** [comment]
Boost 1.74.0
I'm simply adding papilo/src into the include directories, i.e. no cmake involved.
The error ist
```
LINK Pass 1: command "C:\PROGRA~1\MICROS~2\2022\PROFES~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\link.exe /nologo <some linker line full of irrelevant filenames>" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: cannot open file 'libboost_serialization-vc142-mt-gd-x64-1_74.lib'
```

I attach the workaround - as said simply comment out all #include <boost/something> in those 4 files. Maybe it's just working because I don't instantiate any of the templates that require it...
At the end it's just a minor issue to reapply that patch after each update of papilo.

[boost_linker_workaround.patch](https://github.com/scipopt/papilo/files/14439671/boost_linker_workaround.patch)

**Comment by alexhoen** [comment]
Ah, I did not reach the headline carefully and thought you were using it as a standalone library.

In this case, the serialization is not necessary.  

One follow-up question:

Can you check if your Boost installation has the serialization component?

`
-- Found Boost: /home/alexander/src/boost_1_78_0/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found version "1.78.0") found components: iostreams serialization program_options `

I guess that is optional and hence can lead to some problems.

Nevertheless, I will think about disabling serialization for papilo (lib). We did something similar with program_options.

**Comment by tobiass-sdl** [comment]
I have only the boost headers. No libraries except program_options. The only reason we have program_options is another 3rd party library where the boost libraries. Technically I don't even run cmake in the papilo directory and therefore all checks that might be in there are bypassed.
In our setup any additional dll we have to ship hurts - applying the patch is much easier but that's mostly due to coporate stuff and probably not a common problem.

I would be fine with simply changing the "The executable additionally requires some of the boost runtime libraries that are not required when PaPILO is used as a library." in the Readme.

**Comment by ju-manns** [comment]
Hi @tobiass-sdl Which boost version are you using? I tested with boost 1.73 and it ships serialization by default.

**Comment by tobiass-sdl** [comment]
Hallo,

Ich vermute, wir können auf Deutsch reden.

Es geht darum, dass die Readme von papilo behauptet, man bräuchte wenn man papilo als Bibliothek nutzt keine nicht-header-only Boost libraries. Das ist offensichtlich falsch.

In unserem Setup haben wir wirklich nur die header von boost 1.74.0, die man z.B. unter https://boostorg.jfrog.io/artifactory/main/release/1.74.0/source/ herunterladen kann. Die boost libraries zu installieren + linken ist selbstverständlich technisch möglich, aber wenn man in den Regeln eines DAX-Konzerns gefangen ist deutlich aufwendiger als den Patch anzuwenden. Jede CVE in Drittsoftware macht uns Arbeit und bei boost ist durchaus eine Wahrscheinlichkeit da, dass jemand eine CVE beantragt. Außerdem muss sichergestellt sein, dass alle notwendigen boost dlls mit unserer Software ausgeliefert werden. Alles machbar aber Aufwand...

Wie schon im Ticket gesagt ist es völlig in Ordnung, wenn ihr einfach die Readme korrigiert und wir pflegen den patch einfach bei uns lokal, da unser Anwendungsfall recht speziell ist und der patch uns vielleicht 5min bei jedem Papiloupdate kostet. Bei der Updatefrequenz von Papilo ist das sehr überschaubar.

Tobias

**Comment by alexhoen** [comment]
We would rather tend to use preprocessor variables like `Boost_SERIALIZATION_FOUND` to disable the libs coming from serialization. Then it should work in both cases.
It would we great if you could test a patch that we could provide next week.

**Comment by tobiass-sdl** [comment]
works fine, thanks.

**Comment by alexhoen** [comment]
thanks for reporting
