### ISSUE TITLE
Typo breaking build without GMP

### ISSUE THREAD

**Issue by chrjabs** [scipopt/papilo#51]
When building without GMP (`-DGMP=OFF`), I get the following error:
```
scipoptsuite-9.0.1/papilo/src/papilo/misc/MultiPrecision.hpp:142:35: error: #if with no expression
  142 | #if PAPILO_SERIALIZATION_AVAILABLE
      |                                   ^
```
I assume there should be an `#ifdef` on the following line, at least that fixes the build for me.
https://github.com/scipopt/papilo/blob/e9f94e45e8513efbd583dbcde8bb60694f2f41b8/src/papilo/misc/MultiPrecision.hpp#L142

**Comment by alexhoen** [comment]
Thanks a lot for providing the fix.

I merged your commit to the internal repository and it should be mirrored back soonish.
