### ISSUE TITLE
HighsInterface.hpp:97:13: error: ‘class HighsLp’ has no member named ‘a_index_’

### ISSUE THREAD

**Issue by caelumspace** [scipopt/papilo#55]
The HighsInterface.hpp is calling outdated methods on the HighsLp model.

There was a PR for this error back in 2022 but the error remains in both branches. 
https://github.com/scipopt/papilo/pull/22

Could this interface be brought up to date so it can compile against the latest HiGHs?

**Comment by alexhoen** [comment]
The merge request you are referring to was rebased to our internal repository and merged there. _(an explanation why it is closed in this repo)_

PaPILO definitely works until version HIGHS 1.6. What version are you using? 

Updating it to 1.7 is not the highest priority on our list, but we would welcome any contribution :smile:

**Comment by alexhoen** [comment]
We updated the HighsInterface and adjusted the build system so that you can now integrate also Highs 1.7.x. 
If you still have problems please come back to us.
