### ISSUE TITLE
Are the values of the solutions to the original problem and the reduced problem equal?

### ISSUE THREAD

**Issue by linpeng0105** [scipopt/papilo#58]
A MIP problem **A.mps**, after PAPILO reduction generates a reduced problem **B.mps**.  
I solved **B.mps** and obtained a solution **B.sol**, with an objective function value of **Value(B)**.  
After the postsolve process, **B.sol** was used to obtain **A.sol,** with an objective function value of **Value(A)**.  

My question: Is **Value(A)** equal to **Value(B)**?

**Comment by alexhoen** [comment]
yes the reduced problem has the same objective value as the original problem, since the objective function is updated after certain transaction to be consistent

**Comment by linpeng0105** [comment]
Thank you very much!
