### ISSUE TITLE
Close to infinite loop in ParallelColDetection

### ISSUE THREAD

**Issue by jjhforrest** [scipopt/papilo#59]
While testing papilo on a problem I had to kill it after more than a day. 
starting presolve of problem /tmp/va.mps with dual-postsolve de-activated
  rows:     8062
  columns:  22012
  int. columns:  22012
  cont. columns:  0
  nonzeros: 52112

round 0   ( Trivial  ):  207 del cols,   22 del rows,  208 chg bounds,    0 chg sides,    0 chg coeffs,    0 tsx applied,    0 tsx conflicts
round 1   (   Fast   ):  234 del cols,   26 del rows,  277 chg bounds,   32 chg sides,   27 chg coeffs,  165 tsx applied,   88 tsx conflicts
round 2   (   Fast   ):  234 del cols,   26 del rows,  558 chg bounds,   32 chg sides,   27 chg coeffs,  727 tsx applied,   88 tsx conflicts
round 3   (   Fast   ):  234 del cols,   26 del rows, 1662 chg bounds,   32 chg sides,   27 chg coeffs, 2935 tsx applied,   88 tsx conflicts
^C
real	2256m46.405s
user	2256m2.292s
sys	0m3.612s

The problem seems to be at
Thread 1 "cbc" received signal SIGINT, Interrupt.
papilo::ParallelColDetection<double>::findParallelCols(papilo::Num<double> const&, int const*, int, papilo::ConstraintMatrix<double> const&, std::vector<double, std::allocator<double> > const&, papilo::VariableDomains<double> const&, papilo::SymmetryStorage const&, bool, papilo::Reductions<double>&)::{lambda(int, int, double const&)#1}::operator()(int, int, double const&) const (__closure=0x7fffffff4110, col1=14407, col2=14406, scale2=@0x7fffffff40f0: 1) at /home/john/scipoptsuite-9.1.0/papilo/src/papilo/presolvers/ParallelColDetection.hpp:236
(gdb) p lbs[14406]@2
$5 = {-0, -0}
(gdb) p ubs[14406]@2
$6 = {889440, 889440}
(gdb) p col1val
$7 = 49775
(gdb) p col2val
$8 = 929663
I can fix the problem by returning if a count gets too large, but I don't know enough about the code to really fix it.

**Comment by DominikKamp** [comment]
There was a recent fix in parallel column detection. You are using the latest main version, right? In `checkDomainsForHoles()` one can safely return `true` if the ranges are too large, in which case just no parallelism will be detected for this pair of columns.

**Comment by DominikKamp** [comment]
Actually, these loops are not necessary. We can directly check whether there are holes based on the scale and the bounds. I will provide a fix.

**Comment by DominikKamp** [comment]
@jjhforrest Here is a possible fix.

[parallelcols.patch](https://github.com/user-attachments/files/16917083/parallelcols.patch)

Would you check whether this works for you?

**Comment by jjhforrest** [comment]
Line 106 of parallelcols.patch is wrong.
+   auto checkDomainForHoles = [&]( int col, const REAL& scale )

but once I changed that to
 auto checkDomainsForHoles = [&]( int col, const REAL& scale )

it worked and solved in seconds.

Thanks.

I don't think the assert at line 572 of SparseStorage.hpp is correct.

**Comment by DominikKamp** [comment]
I changed the name of the function since we only check for holes in the domain of the merged variable.

The assertion
~~~
assert( nRows == 0 );
~~~
indeed looks strange.

**Comment by DominikKamp** [comment]
It seems like this constructor of SparseStorage with the assertion is not required and could be deleted completely.

Thank you very much for the hints!

I will leave the issue open until the fix is merged.

**Comment by DominikKamp** [comment]
The issues are resolved with d942d4e974c9ec5b6aad2661f3b7e8358a4c43d9.
