### ISSUE TITLE
Compilation fails with `‘gcd’ is not a member of ‘boost’`.

### ISSUE THREAD

**Issue by Viech** [scipopt/papilo#6]
Building SCIPOptSuite from source with [this recipe](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=scipoptsuite&id=ba9e8797b878b3dbd2553e3860259c1c2195efcd), and also when that recipe is updated to use version `8.0.0`, compilation fails on my end with the following two errors:

```
/[…]/scipoptsuite-8.0.0/papilo/src/papilo/presolvers/SimplifyInequalities.hpp:144:21: error: ‘gcd’ is not a member of ‘boost’
  144 |       return boost::gcd( static_cast<int64_t>( val1 ),
```
```
/[…]/scipoptsuite-8.0.0/papilo/src/papilo/presolvers/SimplifyInequalities.hpp:164:21: error: ‘gcd’ is not a member of ‘boost’
  164 |       return boost::gcd( static_cast<int64_t>( val1 * multiplier ),
```

This is on Arch Linux (rolling, last full update today).

Replacing both occurences of `boost::gcd` with `boost::integer::gcd` appears to resolve this issue for me (i.e. the build of `papilo-core` succeeds, though there is now a new error in a different part of SCIPOptSuite).

**Comment by 1hoen** [comment]
can you please provide the boost version that you are using?

**Comment by Viech** [comment]
That would be `1.78.0`.

**Comment by 1hoen** [comment]
We recommend using Boost version 1.72 since we run our tests with this version.  Could you please use this version for the build and give us feedback?
Nevertheless, some tests use versions 1.74/1.76 and successfully manage to execute the build, so you could use one of these versions as well.

**Comment by Viech** [comment]
Older versions of boost are not readily available on Arch Linux and a quick attempt to compile one from source failed. Since you are already testing with three versions, it would likely be much easier for you to test also with a more recent one once it is available for your test runner.

What I can add is that I still have SCIPOptSuite `7.0.1` installed, which I compiled successfully with an earlier version of the recipe I mentioned above, i.e. that recipe used to work in the past.

**Comment by fschloesser** [comment]
We will check this with boost 1.78 and scip 8.0.0 and report back to you.

Your scipoptsuite 7.0.1 was likely not compiled with such a fresh boost, right?

**Comment by Viech** [comment]
> Your scipoptsuite 7.0.1 was likely not compiled with such a fresh boost, right?

Almost certainly: Arch's boost was bumped from `1.76.0` to `1.78.0` on 2021-12-17, three months after SCIPOptSuite `7.0.3` was released.

On my other computer running Arch I have SCIPOptSuite `7.0.3` installed, which would have been compiled with either boost `1.75.0` to `1.76.0` at the time. Since I've also tried to compile `7.0.3` using boost `1.78.0` before I opened this issue, getting the same error, the problem is very likely caused by that boost version.

**Comment by fschloesser** [comment]
We tested this with both 1.77 and 1.78, it seems that the problem started occuring with version 1.78. We'll let you know when this is fixed. Thanks for reporting!

**Comment by 1hoen** [comment]
Unfortunately, besides the above-mentioned build error using Boost 1.78 in PaPILO triggered also some bugs when presolving with rational precision resulting in false reduced problems.
We fixed these and will provide you with an update next week. 
Please report if the update will fix the problem. 
Thank you for reporting the problem.

**Comment by Viech** [comment]
Great! Did you also come across a number of "cannot convert … to …" build failures in GCG (related to `graph.find_automorphisms`)? Otherwise I will report those separately.

**Comment by 1hoen** [comment]
No, unfortunately not. I would be great if you could report these separately.

**Comment by Viech** [comment]
Will do. The errors are from `scipoptsuite-8.0.0/gcg/`; do I send to a mail to the address listed [here](https://gcg.or.rwth-aachen.de/)?

**Comment by 1hoen** [comment]
exactly, please write a mail at gcg-bugs@or.rwth-aachen.de

**Comment by 1hoen** [comment]
the fix for your problem was released within the week. Hope it works for you now.

**Comment by Viech** [comment]
Thank you! I'll wait on a response and fix from the GCG team before I test so that I can actually compile and test the whole thing.
