### ISSUE TITLE
How to use PAPILO library by Cmake

### ISSUE THREAD

**Issue by linpeng0105** [scipopt/papilo#63]
I need your help!
I build papilo and install papilo in a special path.

I need to use such classes:
papilo::Presolve<REAL>
papilo::Problem<REAL>
papilo::Postsolve<REAL>

Can you provide a simple cmakelist.txt code model to show how integrate papilo into my CPP project?

Thank you very much!

**Comment by alexhoen** [comment]
PaPILO is already integrated in SoPlex and SCIP. I would recommend to check out SoPlex and see how it is integrated there:
https://github.com/scipopt/soplex

especially the CMakeList

https://github.com/scipopt/soplex/blob/master/CMakeLists.txt

**Comment by linpeng0105** [comment]
thank you so much
