### ISSUE TITLE
Papilo Compiling Error in Arch WSL

### ISSUE THREAD

**Issue by chemrgineer** [scipopt/papilo#9]
Hi, for testing purpose I installed Arch WSL that always have latest version of libraries in linux. I installed some required packages and compiled IPOPT without any problem. Then, I moved on SCIP and started compiling from Papilo. I directly pulling github files with clone command.
[log1.txt](https://github.com/scipopt/papilo/files/8790672/log1.txt) file is output of "cmake .." command.

[log2.txt](https://github.com/scipopt/papilo/files/8790674/log2.txt) file is output of "make -j12" command.
I also attaching CMake log files.
[CMakeError.log](https://github.com/scipopt/papilo/files/8790675/CMakeError.log)
[CMakeOutput.log](https://github.com/scipopt/papilo/files/8790677/CMakeOutput.log)
 
I think these files will be helpful to identify error.

**Comment by alexhoen** [comment]
Hi,
these errors are thrown from the files of the Boost Library, hence something might be wrong with the installation. 
Did you compile and test Boost yourself?

**Comment by alexhoen** [comment]
we do not test on Arch Linux, but other users were able to run PaPILO on Arch Linux (after some issues with the newest Boost version were fixed): https://github.com/scipopt/papilo/issues/6

Did you test that the Boost Version works properly? You can maybe checkout the SoPlex repro and try to build it?

**Comment by ambros-gleixner** [comment]
Please reopen if you need any further help with your build.
